Repository FRONT-END-BOOTCAMP-PLUS-4/change_me, pull requests merged in 2025-04, with the labels that each got.

#25 [Fix/#24] : 마이페이지에서 회원가입한 시간 세계시로 표현되는 부분 한국시로 나오도록 수정
  app/(member)/layout.tsx
  app/(member)/login/page.tsx
  app/profile/components/ProfileForm.tsx
Labels: feat

#29 [feat/#26] 로그인, 로그아웃시 쿠키에 토큰 저장하는 걸 로컬스토리지에 토큰 저장하고 삭제하는 걸로 변경
  app/(members)/login/componenets/LoginForm.tsx
  app/api/members/login/route.ts
  app/api/members/logout/route.ts
  app/api/members/profile/route.ts
  app/profile/components/LogoutButton.tsx
  app/profile/page.tsx
Labels: feat

#36 [style/#35] 컨벤션을 위해 자기가 쓰는 파일명 수정
  app/(members)/login/componenets/LoginForm.tsx
  app/api/members/join/route.ts
  app/api/members/login/route.ts
  app/api/members/profile/route.ts
  app/common-components/ClientLayoutWrapper.tsx
  app/profile/components/LogoutButton.tsx
  application/usecase/member/Dto/GetProfileDTO.ts
  application/usecase/member/Dto/JoinMemberDTO.ts
  application/usecase/member/Dto/LoginMemberDTO.ts
  application/usecase/member/Dto/LogoutMemberDTO.ts
  application/usecase/member/Dto/UpdateProfileDTO.ts
  application/usecase/member/Dto/WithdrawMemberDTO.ts
  application/usecase/member/GetProfileUsecase.ts
  application/usecase/member/JoinMemberUsecase.ts
  application/usecase/member/LoginMemberUsecase.ts
  application/usecase/member/LogoutMemberUsecase.ts
  application/usecase/member/UpdateProfileUsecase.ts
  application/usecase/member/WithdrawMemberUsecase.ts
Labels: file

#41 [Refactor/#39]: DTO.ts 파일 이름 수정
  app/api/messages/route.ts
  application/usecase/like/Dto/CreateLikeDTO.ts
  application/usecase/message/GetMessageListUsecase.ts
Labels: refactor

#42 [feat/#38] 멤버엔티티에 기본값만 있도록 수정
  application/usecase/member/GetProfileUsecase.ts
  application/usecase/member/JoinMemberUsecase.ts
  application/usecase/member/LoginMemberUsecase.ts
  domain/entities/Member.ts
  infra/repositories/supabase/SbMemberRepository.ts
Labels: refactor

#44 [feat/#34] 카테고리 관리자 조회
  app/api/admin/categories/[id]/route.ts
  app/api/admin/categories/route.ts
  app/api/categories/route.ts
  application/usecase/category/GetAdminCategoryListUsecase.ts
  application/usecase/category/GetCategoryListUsecase.ts
  application/usecase/category/dto/AdminCategoryListDto.ts
  application/usecase/category/dto/GetAdminCategoryListQueryDto.ts
  infra/repositories/supabase/SbCategoryRepository.ts
  utils/supabase/Server.ts
Labels: feat

#46 [feat/#43] 회원가입 기능(CSS제외, 이메일중복검사 추가, 비밀번호 확인란 추가)
  app/(members)/signup/components/SignUpForm.tsx
  app/api/members/email-check/route.ts
  application/usecase/member/CheckEmailDuplicateUsecase.ts
  application/usecase/member/JoinMemberUsecase.ts
  domain/entities/Member.ts
  domain/repositories/MemberRepository.ts
  infra/repositories/supabase/SbMemberRepository.ts
Labels: feat

#51 [feat/#50] 로그인 완성(CSS제외)
  app/(members)/login/components/LoginForm.tsx
  app/(members)/login/page.tsx
Labels: refactor

#53 [Feat/#52] 마이페이지에서 회원탈퇴기능 추가
  app/api/members/withdraw/route.ts
  app/profile/components/WithdrawButton.tsx
  app/profile/page.tsx
  application/usecase/member/LoginMemberUsecase.ts
  application/usecase/member/WithdrawMemberUsecase.ts
  domain/repositories/MemberRepository.ts
  infra/repositories/supabase/SbMemberRepository.ts
Labels: feat

#54 [feat/#45] 카테고리 등록 기능
  app/api/admin/categories/route.ts
  app/api/categories/route.ts
  application/usecase/category/CreateCategoryUsecase.ts
  application/usecase/category/dto/CreateCategoryDto.ts
  domain/repositories/CategoryRepository.ts
  infra/repositories/supabase/SbCategoryRepository.ts
  utils/auth.ts
Labels: feat

#63 [Feat/#55] 프로필 변경(비밀번호 확인 후 닉네임, 이미지 변경) 기능 추가
  app/(members)/login/components/LoginForm.tsx
  app/api/members/password/route.ts
  app/api/members/profile-image/route.ts
  app/api/members/verify-password/route.ts
  app/profile/components/ProfileForm.tsx
  application/usecase/member/GetProfileUsecase.ts
  application/usecase/member/UpdateProfileUsecase.ts
  domain/repositories/MemberRepository.ts
  infra/repositories/supabase/SbMemberRepository.ts
  next.config.ts
Labels: feat

#65 [feat/#64] 프로필 변경시 수정일도 변경되는 기능 추가
  infra/repositories/supabase/SbMemberRepository.ts
Labels: feat, chore

#66 [Feat/#56] 카테고리 수정 및 api 요청 권한 검사 기능
  app/api/admin/categories/[id]/route.ts
  app/api/admin/categories/route.ts
  application/usecase/category/UpdateCategoryUsecase.ts
  application/usecase/category/dto/UpdateCategoryDto.ts
  application/usecase/member/LoginMemberUsecase.ts
  domain/repositories/CategoryRepository.ts
  infra/repositories/supabase/SbCategoryRepository.ts
  middleware.ts
  package-lock.json
  package.json
  utils/auth.ts
  utils/jwt.ts
Labels: feat

#69 [feat/#68] 카테고리 삭제 기능
  app/api/admin/categories/[id]/route.ts
  application/usecase/category/DeleteCategoryUsecase.ts
  application/usecase/category/UpdateCategoryUsecase.ts
  domain/repositories/CategoryRepository.ts
  infra/repositories/supabase/SbCategoryRepository.ts
Labels: feat

#70 [feat/#67] 로그인 후 프로필페이지로 이동안되고 다시 로그인페이지로 오는 부분 수정, 프로필페이지 수정안되던 버그 수정
  app/profile/components/ProfileForm.tsx
  application/usecase/member/GetProfileUsecase.ts
  middleware.ts
Labels: fix

#74 [Feat/#72] 비밀번호 변경 페이지 제작 및 기능 동작
  app/api/members/change-password/route.ts
  app/api/members/verify-password/route.ts
  app/profile/components/ChangePasswordButton.tsx
  app/profile/page.tsx
  app/profile/password-change/components/PasswordChangeForm.tsx
  app/profile/password-change/page.tsx
  application/usecase/member/WithdrawMemberUsecase.ts
  domain/repositories/MemberRepository.ts
  infra/repositories/supabase/SbMemberRepository.ts
Labels: feat

#79 [refactor/#76] 미들웨어에서 검사하는 부분 기존 코드에서 제거 및 getMemberIdFromToken 이용하도록 수정
  app/api/members/change-password/route.ts
  app/api/members/profile/route.ts
  app/api/members/verify-password/route.ts
  app/api/members/withdraw/route.ts
  app/profile/page.tsx
Labels: refactor

#81 [feat/#73] header 컴포넌트 작성
  app/(members)/layout.tsx
  app/common-components/ClientLayoutWrapper.tsx
  app/components/HeaderIcon.module.scss
  app/components/HeaderIcon.tsx
  app/components/RootHeader.module.scss
  app/components/RootHeader.tsx
  app/globals.css
  app/layout.tsx
  app/page.tsx
  stores/memberStore.ts
Labels: feat

#82 [style/#80] 회원가입페이지 css(작업중)
  app/(members)/signup/components/SignUpForm.module.scss
  app/(members)/signup/components/SignUpForm.tsx
Labels: chore

#85 [feat/#83] 레이아웃 및 라우트 재정비
  app/(auth)/layout.module.scss
  app/(auth)/layout.tsx
  app/(auth)/login/components/LoginForm.tsx
  app/(auth)/login/page.tsx
  app/(auth)/signup/components/SignUpForm.module.scss
  app/(auth)/signup/components/SignUpForm.tsx
  app/(auth)/signup/page.tsx
  app/(members)/layout.tsx
  app/(members)/signup/layout.tsx
  app/(users)/components/HeaderIcon.module.scss
  app/(users)/components/HeaderIcon.tsx
  app/(users)/components/UserHeader.module.scss
  app/(users)/components/UserHeader.tsx
  app/(users)/daily-routine/page.tsx
  app/(users)/layout.tsx
  app/(users)/message/page.tsx
  app/(users)/page.module.css
  app/(users)/page.tsx
  app/(users)/profile/components/ChangePasswordButton.tsx
  app/(users)/profile/components/LogoutButton.tsx
  app/(users)/profile/components/ProfileForm.tsx
  app/(users)/profile/components/WithdrawButton.tsx
  app/(users)/profile/page.tsx
  app/(users)/profile/password-change/components/PasswordChangeForm.tsx
  app/(users)/profile/password-change/page.tsx
  app/(users)/record/page.tsx
  app/admin/layout.tsx
  app/admin/page.tsx
  app/components/RootHeader.module.scss
  app/globals.css
  app/layout.tsx
Labels: feat

#87 [style/#86] 바뀐 폴더 구조이후 기능 동작 테스트 및 오류 발생시 수정, 안쓰는 파일 정리
  app/(auth)/signup/components/SignUpForm.module.scss
  app/(auth)/signup/components/SignUpForm.tsx
  app/api/members/logout/route.ts
  application/usecase/member/LogoutMemberUsecase.ts
  application/usecase/member/dto/GetProfileDto.ts
  application/usecase/member/dto/LogoutMemberDto.ts
Labels: refactor

#89 [refactor/#88] 회원가입 로직 dto사용하도록 수정하기
  app/api/members/join/route.ts
  application/usecase/member/JoinMemberUsecase.ts
Labels: refactor

#91 [refactor/#90] 폴더 구조 변경
  app/(base)/components/BaseHeader.module.scss
  app/(base)/components/BaseHeader.tsx
  app/(base)/components/HeaderIcon.module.scss
  app/(base)/components/HeaderIcon.tsx
  app/(base)/layout.tsx
  app/(base)/member/daily-routine/page.tsx
  app/(base)/member/message/page.tsx
  app/(base)/member/profile/components/ChangePasswordButton.tsx
  app/(base)/member/profile/components/LogoutButton.tsx
  app/(base)/member/profile/components/ProfileForm.tsx
  app/(base)/member/profile/components/WithdrawButton.tsx
  app/(base)/member/profile/page.tsx
  app/(base)/member/profile/password-change/components/PasswordChangeForm.tsx
  app/(base)/member/profile/password-change/page.tsx
  app/(base)/member/record/page.tsx
  app/(base)/page.module.css
  app/(base)/page.tsx
  app/api/email-check/route.ts
  app/api/habits/[id]/giveup/route.ts
  app/api/habits/[id]/route.ts
  app/api/habits/route.ts
  app/api/join/route.ts
  app/api/login/route.ts
  app/api/members/habits/[id]/giveup/route.ts
  app/api/members/habits/[id]/route.ts
  app/api/members/habits/route.ts
  app/api/members/likes/[messageId]/route.ts
  app/api/members/likes/route.ts
  app/api/members/messages/[id]/route.ts
  app/api/members/messages/route.ts
  app/api/members/records/[habitId]/route.ts
  app/api/members/records/route.ts
  app/components/CategoryDropdown.tsx
  app/components/ClientLayoutWrapper.tsx
  app/components/HabitDetailModal.tsx
  app/components/Pager.module.scss
  app/components/Pager.tsx
  app/components/Toast.tsx
  app/layout.tsx
  middleware.ts
Labels: refactor

#93 [refactor/#92] 폴더구조 변경 이후 회원 기능 동작 테스트 및 오류발생시 해결
  app/(auth)/login/components/LoginForm.tsx
  app/(auth)/signup/components/SignUpForm.tsx
  app/(base)/member/profile/password-change/components/PasswordChangeForm.tsx
Labels: chore

#96 [Refactor/#94] 로그인, 마이페이지 로직 dto사용하도록 수정하기 + DM 좋아요 아이콘 추가
  app/api/login/route.ts
  app/api/members/profile-image/route.ts
  application/usecase/member/GetProfileUsecase.ts
  application/usecase/member/LoginMemberUsecase.ts
  application/usecase/member/UpdateProfileUsecase.ts
  application/usecase/member/dto/GetProfileDto.ts
  application/usecase/member/dto/UpdateProfileDto.ts
  application/usecase/member/dto/WithdrawMemberDto.ts
  public/images/EmptyHeart.png
  public/images/FullHeart.png
Labels: chore

#98 [style/#97] 회원가입페이지 css
  app/(auth)/layout.module.scss
  app/(auth)/signup/components/SignUpForm.module.scss
  app/(auth)/signup/components/SignUpForm.tsx
Labels: chore

#105 [refactor/#102] sbMemberRepository.ts 구조 수정하기
  app/api/email-check/route.ts
  app/api/join/route.ts
  app/api/login/route.ts
  app/api/members/change-password/route.ts
  app/api/members/profile-image/route.ts
  app/api/members/profile/route.ts
  app/api/members/verify-password/route.ts
  app/api/members/withdraw/route.ts
  application/usecase/member/ChangePasswordUsecase.ts
  application/usecase/member/CheckEmailDuplicateUsecase.ts
  application/usecase/member/GetProfileUsecase.ts
  application/usecase/member/JoinMemberUsecase.ts
  application/usecase/member/LoginMemberUsecase.ts
  application/usecase/member/UpdateProfileUsecase.ts
  application/usecase/member/VerifyPasswordUsecase.ts
  application/usecase/member/WithdrawMemberUsecase.ts
  domain/repositories/MemberRepository.ts
  infra/repositories/supabase/SbMemberRepository.ts
Labels: refactor

#109 [Style/#108] 마이페이지 css, 마이페이지에서 프로필정보 가져오는 부분, 탈퇴하기에서 getMemberIdFromToken 사용하도록 수정
  app/(base)/member/profile/components/ChangePasswordButton.module.scss
  app/(base)/member/profile/components/ChangePasswordButton.tsx
  app/(base)/member/profile/components/ProfileForm.module.scss
  app/(base)/member/profile/components/ProfileForm.tsx
  app/(base)/member/profile/components/WithdrawButton.module.scss
  app/(base)/member/profile/components/WithdrawButton.tsx
  app/(base)/member/profile/page.module.scss
  app/(base)/member/profile/page.tsx
  app/api/members/profile/route.ts
  app/api/members/withdraw/route.ts
  application/usecase/member/GetProfileUsecase.ts
  application/usecase/member/WithdrawMemberUsecase.ts
Labels: chore

#110 [Feat/#104] 공통 컴포넌트 작성
  app/(auth)/login/components/LoginForm.tsx
  app/(base)/layout.tsx
  app/(base)/member/message/page.tsx
  app/(base)/member/profile/components/LogoutButton.tsx
  app/(base)/page.tsx
  app/admin/layout.tsx
  app/admin/page.tsx
  app/components/ClientLayoutWrapper.tsx
  app/components/Header.module.scss
  app/components/Header.tsx
  app/components/HeaderIcon.module.scss
  app/components/HeaderIcon.tsx
  app/components/Pager.module.scss
  app/components/Pager.tsx
  application/usecase/category/GetAdminCategoryListUsecase.ts
  stores/MemberStore.ts
Labels: feat, fix

#119 [Fix/#118] pull 이후 기능 오류 수정
  app/(base)/member/profile/components/ProfileForm.tsx
  app/(base)/member/profile/components/WithdrawButton.tsx
  app/(base)/member/profile/page.tsx
  app/(base)/member/profile/password-change/components/PasswordChangeForm.tsx
  app/api/join/route.ts
  application/usecase/member/JoinUsecase.ts
Labels: fix

#121 [fix/#120] 비밀번호변경페이지 css
  app/(base)/member/profile/password-change/components/PasswordChangeForm.module.scss
  app/(base)/member/profile/password-change/components/PasswordChangeForm.tsx
Labels: chore

#123 [Feat/#122] 모달 및 관리자 페이지 관련 컴포넌트 작성
  app/(base)/member/components/modals/CreateHabitModal.tsx
  app/(base)/member/components/modals/EditHabitModal.tsx
  app/(base)/member/components/modals/ViewHabitModal.tsx
  app/admin/components/CategoryItem.module.scss
  app/admin/components/CategoryItem.tsx
  app/admin/components/CategoryList.module.scss
  app/admin/components/CategoryList.tsx
  app/admin/components/CreateCategoryModal.tsx
  app/admin/components/Title.module.scss
  app/admin/components/Title.tsx
  app/admin/page.module.scss
  app/admin/page.tsx
  app/components/ModalWrapper.module.scss
  app/components/ModalWrapper.tsx
  app/components/Modals.tsx
  app/components/Pager.module.scss
  app/globals.css
  app/layout.tsx
  application/usecase/category/GetAdminCategoryListUsecase.ts
  stores/modalStore.ts
Labels: feat

#127 [Feat/#124] API 연동 관련 fetcher 및 카테고리 관리 api hook 작성
  app/admin/components/CategoryItem.tsx
  app/admin/components/CategoryList.tsx
  app/admin/components/Title.tsx
  hooks/useAdminCategories.ts
  package-lock.json
  package.json
  tsconfig.json
  utils/fetcher.ts
  utils/utils.ts
Labels: feat

#133 [feat/#131] 오늘의 루틴페이지에서 내가 진행중인 습관리스트 전체 나오도록 구현
  app/(base)/member/daily-routine/components/TestHabitList.tsx
  app/(base)/member/daily-routine/page.tsx
  app/api/test-habits/route.ts
  application/usecase/habit/TestGetOngoingHabitsUsecase.ts
  application/usecase/habit/dto/TestHabitProgressDto.ts
  domain/entities/TestHabit.ts
  domain/repositories/HabitRepository.ts
  infra/repositories/supabase/SbHabitRepository.ts
  utils/date.ts
Labels: feat

#135 [feat/#115]: 메시지 페이지 컴포넌트 생성
  app/(auth)/login/components/LoginForm.tsx
  app/(base)/member/message/components/DeleteMessageButton.tsx
  app/(base)/member/message/components/EditMessageButton.tsx
  app/(base)/member/message/components/LikeButton.tsx
  app/(base)/member/message/components/MemberFilterButtons.tsx
  app/(base)/member/message/components/MessageItem.module.scss
  app/(base)/member/message/components/MessageItem.tsx
  app/(base)/member/message/components/MessageList.module.scss
  app/(base)/member/message/components/MessageList.tsx
  app/(base)/member/message/components/WriteMessageButton.tsx
  app/(base)/member/message/components/WriteMessageForm.module.scss
  app/(base)/member/message/components/WriteMessageForm.tsx
  app/(base)/member/message/page.tsx
  app/common-components/Pager.tsx
  application/usecase/message/GetMessageListUsecase.ts
  application/usecase/message/dto/MessageDto.ts
Labels: feat

#136 [Feat/#134] 오늘의 루틴페이지에서 내가 진행중인 습관리스트 습관마다 체크, 체크해제 기능 추가
  app/(base)/member/daily-routine/components/TestHabitList.tsx
  app/api/test-habit-records/checked/route.ts
  app/api/test-habit-records/route.ts
  application/usecase/habit/TestGetTodayCheckedHabitIdsUsecase.ts
  application/usecase/habit/TestHabitRecordUsecase.ts
  application/usecase/habit/dto/TestGetTodayHabitRecordDto.ts
  application/usecase/habit/dto/TestHabitRecordDto.ts
  domain/repositories/HabitRecordRepository.ts
  infra/repositories/supabase/SbHabitRecordRepository.ts
Labels: feat

#138 [Feat/#137] 오늘의 루틴페이지에서 내가 진행중인 습관 삭제 기능 추가(만든 당일만 보이도록)
  app/(base)/member/daily-routine/components/TestHabitList.tsx
  app/api/test-habit-records/checked/route.ts
  app/api/test-habits/[id]/route.ts
  app/common-components/Pager.tsx
  application/usecase/habit/TestDeleteHabitUsecase.ts
  domain/repositories/HabitRepository.ts
  infra/repositories/supabase/SbHabitRepository.ts
Labels: feat

#141 [Feat/#132] 관리자 페이지 api 연동
  app/admin/components/CategoryItem.tsx
  app/admin/components/CategoryList.tsx
  app/admin/components/CategoryModal.module.scss
  app/admin/components/CategoryModal.tsx
  app/admin/components/CreateCategoryModal.tsx
  app/admin/components/Title.module.scss
  app/admin/components/Title.tsx
  app/admin/page.module.scss
  app/admin/page.tsx
  app/components/ModalWrapper.module.scss
  app/components/Modals.tsx
  app/components/Pager.tsx
  app/globals.css
  application/usecase/category/GetAdminCategoryListUsecase.ts
  application/usecase/category/dto/AdminCategoryListDto.ts
  hooks/useAdminCategories.ts
  infra/repositories/supabase/SbCategoryRepository.ts
  stores/modalStore.ts
  utils/fetcher.ts
Labels: feat

#142 [feat/#139] 오늘의 루틴페이지에서 내가 진행중인 습관 포기 기능 구현(80% 전까지만 보이도록)
  app/(base)/member/daily-routine/components/TestHabitList.tsx
  app/api/test-habits/[id]/giveup/route.ts
  application/usecase/habit/TestGetOngoingHabitsUsecase.ts
  application/usecase/habit/TestGiveUpHabitUsecase.ts
  application/usecase/habit/dto/TestHabitProgressDto.ts
  domain/repositories/HabitRepository.ts
  infra/repositories/supabase/SbHabitRepository.ts
Labels: feat

#147 [feat/#145] 오늘의 루틴페이지에서 내가 진행중인 습관 수정 기능 구현, 등록하거나 수정했을 때 리스트에 바로 적용안되…
  app/(base)/member/components/modals/TestCreateHabitModal.tsx
  app/(base)/member/daily-routine/components/TestHabitList.tsx
  app/(base)/member/daily-routine/page.tsx
  app/api/test-habits/[id]/route.ts
  application/usecase/habit/TestUpdateHabitUsecase.ts
  application/usecase/habit/dto/TestUpdateHabitDto.ts
  domain/repositories/HabitRepository.ts
  infra/repositories/supabase/SbHabitRepository.ts
Labels: feat

#149 [Feat/#148] 오늘의 루틴페이지에 습관 수정버튼 80%전까지만 보이도록 수정 및 달성률 실제 체크한 데이터로 계산하도록 수정
  app/(base)/member/daily-routine/components/TestHabitList.tsx
  app/api/test-habits/route.ts
  application/usecase/habit/TestGetOngoingHabitsUsecase.ts
  domain/repositories/HabitRecordRepository.ts
  infra/repositories/supabase/SbHabitRecordRepository.ts
Labels: feat

#151 [feat/#146] HabitRepository 변경
  application/usecase/habit/GetAnonHabitListUsecase.ts
  application/usecase/habit/GetHabitListUsecase.ts
  application/usecase/habit/dto/AnonHabitDto.ts
  application/usecase/habit/dto/AnonHabitListDto.ts
  application/usecase/habit/dto/AnonHabitListQueryDto.ts
  application/usecase/habit/dto/HabitDto.ts
  domain/entities/Habit.ts
  domain/entities/HabitMember.ts
  domain/repositories/HabitRepository.ts
  domain/repositories/filters/HabitFilter.ts
  infra/repositories/supabase/SbHabitRepository.ts
Labels: feat

#157 [Feat/#150] 오늘의 루틴페이지 일차 계산로직 수정, 체크 후 바로 화면에 적용 안되는 현상 수정, 체크할때 달성률 80% 넘을 시 상태 3으로 80%미만시 상태0으로 수정하는 기능 추가, 리스트 보여줄때 0인것만 보여주는 것에서 3인것도 포함하고 종료일 오늘부터 이후인것만 보여주도록 수정
  app/(base)/member/daily-routine/components/TestHabitList.tsx
  app/api/test-habits/[id]/auto-status/route.ts
  application/usecase/habit/TestAutoUpdateHabitStatusUsecase.ts
  application/usecase/habit/TestGetOngoingHabitsUsecase.ts
  application/usecase/habit/dto/TestHabitProgressDto.ts
  domain/repositories/HabitRepository.ts
  infra/repositories/supabase/SbHabitRepository.ts
Labels: feat

#160 [Feat/#158] 오늘의 루틴페이지에서 내가 진행중인 습관리스트 카테고리 별로 구분해서 해당만 나오도록 구현, 머지할 때 충돌로 생긴 오류 수정
  app/(base)/member/daily-routine/components/TestHabitList.tsx
  infra/repositories/supabase/SbHabitRecordRepository.ts
Labels: feat

#161 [fix/#159] 메시지 조회 API 로직 오류 수정
  application/usecase/message/GetMessageListUsecase.ts
Labels: fix

#163 [feat/#156] 모두의 습관 관련 커스텀 훅 작성
  application/usecase/habit/GetAnonHabitListUsecase.ts
  application/usecase/habit/dto/AnonHabitDto.ts
  domain/entities/HabitMember.ts
  hooks/useAnonHabits.ts
  hooks/useCategories.ts
  infra/repositories/supabase/SbHabitRepository.ts
Labels: feat

#165 [Feat/#162] 습관 등록/수정 모달 수정
  app/(base)/member/components/modals/TestCreateHabitModal.tsx
Labels: feat

#167 [feat/#166] 회원가입할때 닉네임, 이름 20자이하로 입력가능하도록 수정
  app/(auth)/signup/components/SignUpForm.tsx
Labels: feat

#169 [feat/#168] 오늘의 루틴 페이지에서 일차 계산 로직 수정(시분초 계산에서 제외)
  application/usecase/habit/TestGetOngoingHabitsUsecase.ts
Labels: feat

#171 [Fix/#130]: 메시지 컴포넌트 수정 1일차
  app/(base)/member/message/components/DeleteMessageButton.tsx
  app/(base)/member/message/components/EditMessageButton.tsx
  app/(base)/member/message/components/LikeButton.tsx
  app/(base)/member/message/components/MemberFilterButtons.module.scss
  app/(base)/member/message/components/MemberFilterButtons.tsx
  app/(base)/member/message/components/MessageButton.tsx
  app/(base)/member/message/components/MessageItem.tsx
  app/(base)/member/message/components/MessageList.tsx
  app/(base)/member/message/components/WriteMessageForm.module.scss
  app/(base)/member/message/components/WriteMessageForm.tsx
  app/(base)/member/message/page.module.scss
  app/(base)/member/message/page.tsx
  app/api/members/messages/route.ts
  application/usecase/member/LoginUsecase.ts
  application/usecase/member/dto/LoggedInDto.ts
  application/usecase/message/GetMessageListUsecase.ts
  application/usecase/message/dto/MessageDto.ts
  hooks/useMessageLikes.ts
  hooks/useMessages.ts
  package-lock.json
  stores/authStore.ts
Labels: feat, fix

#173 [feat/#170] 오늘의 루틴 페이지 css
  app/(base)/member/daily-routine/components/TestHabitList.module.scss
  app/(base)/member/daily-routine/components/TestHabitList.tsx
  app/(base)/member/daily-routine/page.tsx
Labels: chore

#176 [Style/#175] 습관 등록/수정 모달 css 외 2개
  app/(base)/member/components/modals/CreateHabitModal.tsx
  app/(base)/member/components/modals/EditHabitModal.tsx
  app/(base)/member/components/modals/TestCreateHabitModal.module.scss
  app/(base)/member/components/modals/TestCreateHabitModal.tsx
  app/(base)/member/daily-routine/components/TestHabitList.module.scss
  app/(base)/member/daily-routine/components/TestHabitList.tsx
  app/(base)/member/daily-routine/page.tsx
  app/components/Modals.tsx
  stores/modalStore.ts
Labels: refactor

#178 [refactore/#175] 오늘의 루틴페이지에서 습관 체크, 달성률에 따른 상태 변화 api 하나로 통합
  app/(base)/member/daily-routine/components/TestHabitList.tsx
  app/api/test-habit-records/route.ts
  app/api/test-habits/[id]/auto-status/route.ts
  application/usecase/habit/TestAutoUpdateHabitStatusUsecase.ts
  application/usecase/habit/TestHabitRecordUsecase.ts
Labels: refactor

#182 [Feat/#181] 오늘의루틴페이지에서 로딩일때 처리 추가
  app/(base)/member/daily-routine/components/TestHabitList.tsx
  app/components/Loading.module.scss
  app/components/Loading.tsx
  public/images/Loading.png
Labels: chore

#183 [feat/#172]: 메시지 작성 기능 추가
  app/(base)/member/message/components/LikeButton.tsx
  app/(base)/member/message/components/MemberFilterButtons.tsx
  app/(base)/member/message/components/MessageButton.tsx
  app/(base)/member/message/components/MessageForm.module.scss
  app/(base)/member/message/components/MessageForm.tsx
  app/(base)/member/message/components/MessageItem.tsx
  app/(base)/member/message/components/MessageList.module.scss
  app/(base)/member/message/components/MessageList.tsx
  app/(base)/member/message/components/WriteMessageButton.tsx
  app/(base)/member/message/components/WriteMessageForm.tsx
  app/(base)/member/message/page.tsx
  app/api/members/messages/route.ts
  hooks/useMessages.ts
Labels: feat, fix

#193 [fix/#187] 메시지 폼 유저 정보 API에서 가져오게 변경
  app/(base)/member/message/components/MessageForm.tsx
Labels: fix

#196 [fix/#190] Toast 추가 및 css 및 Store 추가
  app/(auth)/login/components/LoginForm.tsx
  app/components/Toast.module.scss
  app/components/Toast.tsx
  app/layout.tsx
  stores/toastStore.ts
Labels: feat

#199 [style/#197] 로딩페이지 css 수정
  app/components/Loading.module.scss
Labels: chore

#211 [refactor/#200] MessageButton 모듈 삭제
  app/(base)/member/message/components/MessageButton.tsx
  app/(base)/member/message/components/MessageItem.module.scss
  app/(base)/member/message/components/MessageItem.tsx
Labels: refactor

#222 Refactor/#192 : Habit-status : 1 실패 불가 결정 이후 로직 변경
  infra/repositories/supabase/SbHabitRepository.ts
Labels: refactor

#223 [style/#221] 습관명, 설명 한줄로 나오고 넘으면... 처리, 마우스 호버시 전체내용 나옴
  app/(base)/member/daily-routine/components/TestHabitList.module.scss
  app/(base)/member/daily-routine/components/TestHabitList.tsx
Labels: chore

#227 [file/#224] 오늘의 루틴페이지 관련 앞에 Test붙은거 제거하고 동작 잘되는지 테스트
  app/(base)/member/components/modals/HabitModal.module.scss
  app/(base)/member/components/modals/HabitModal.tsx
  app/(base)/member/daily-routine/components/HabitList.module.scss
  app/(base)/member/daily-routine/components/HabitList.tsx
  app/(base)/member/daily-routine/page.tsx
  app/api/members/test-habit-records/checked/route.ts
  app/api/members/test-habit-records/route.ts
  app/api/members/test-habits/[id]/giveup/route.ts
  app/api/members/test-habits/[id]/route.ts
  app/api/members/test-habits/route.ts
  app/components/Modals.tsx
  application/usecase/habit/CreateHabitUsecase.ts
  application/usecase/habit/DeleteHabitUsecase.ts
  application/usecase/habit/GetOngoingHabitsUsecase.ts
  application/usecase/habit/GetTodayCheckedHabitIdsUsecase.ts
  application/usecase/habit/GiveUpHabitUsecase.ts
  application/usecase/habit/HabitRecordUsecase.ts
  application/usecase/habit/TestGetFailHabitsUsecase.ts
  application/usecase/habit/TestGetGiveupHabitsUsecase.ts
  application/usecase/habit/TestGetSuccessHabitsUsecase.ts
  application/usecase/habit/TestGetTodayCheckedHabitIdsUsecase.ts
  application/usecase/habit/TestUpdateHabitUsecase.ts
  application/usecase/habit/UpdateHabitUsecase.ts
  application/usecase/habit/dto/CreateHabitDto.ts
  application/usecase/habit/dto/GetTodayHabitRecordDto.ts
  application/usecase/habit/dto/HabitProgressDto.ts
  application/usecase/habit/dto/TestHabitRecordDto.ts
  application/usecase/habit/dto/UpdateHabitDto.ts
  domain/repositories/HabitRecordRepository.ts
  domain/repositories/HabitRepository.ts
  infra/repositories/supabase/SbHabitRecordRepository.ts
  infra/repositories/supabase/SbHabitRepository.ts
Labels: file

#229 [file/#228] SbHabitRecordRepository.ts와 SbHabitRepository.ts에서 메서드명 통일
  application/usecase/habit/GetOngoingHabitsUsecase.ts
  application/usecase/habit/GetTodayCheckedHabitIdsUsecase.ts
  domain/repositories/HabitRecordRepository.ts
  domain/repositories/HabitRepository.ts
  infra/repositories/supabase/SbHabitRecordRepository.ts
  infra/repositories/supabase/SbHabitRepository.ts
Labels: chore

#231 [feat/#226] habitid에 따른 습관 기록 조회 API, Usecase, Dto 작성
  app/api/members/records/[habitId]/route.ts
  application/usecase/record/GetRecordUsecase.ts
  application/usecase/record/dto/GetRecordDto.ts
  application/usecase/record/dto/RecordDto.ts
Labels: feat

#232 [feat/#230] 오늘의 루틴페이지에서 습관 생성일로 정렬되도록 수정
  infra/repositories/supabase/SbHabitRepository.ts
Labels: chore

#234 [feat/#233] 습관 등록 가능 최소날짜 15일 -> 14일로 수정, 오늘의루틴&습관등록/수정 알림창 토스트로 변경
  app/(base)/member/components/modals/HabitModal.tsx
  app/(base)/member/daily-routine/components/HabitList.tsx
Labels: chore

#236 [feat/#235] 토스트 css 수정
  app/components/Toast.module.scss
Labels: chore

#238 [feat/#237] 회원가입페이지, 마이페이지, 비밀번호변경페이지에서 알림창 토스트로 수정하기
  app/(auth)/signup/components/SignUpForm.tsx
  app/(base)/member/profile/components/ProfileForm.tsx
  app/(base)/member/profile/components/WithdrawButton.tsx
  app/(base)/member/profile/password-change/components/PasswordChangeForm.tsx
  app/admin/components/CategoryModal.tsx
Labels: chore

#240 [feat/#239] 기록보기 페이지 밑에 달성/포기/실패 습관 갯수 추가
  app/(base)/member/record/components/TestRecordList.module.scss
  app/(base)/member/record/components/TestRecordList.tsx
Labels: feat, chore

#241 [feat/#215] 모두의 습관 페이지 스타일링 변경
  app/(base)/components/BottomSection.module.scss
  app/(base)/components/BottomSection.tsx
  app/(base)/components/HabitCard.module.scss
  app/(base)/components/HabitCard.tsx
  app/(base)/components/TopSection.module.scss
  app/(base)/page.module.scss
  app/admin/page.module.scss
  app/components/Header.module.scss
  app/globals.css
  application/usecase/habit/GetAnonHabitListUsecase.ts
Labels: feat

#244 [style/#243] 회원가입, 로그인페이지 화면 위로 쏠림 현상 수정, 회원가입페이지 css수정
  app/(auth)/layout.module.scss
  app/(auth)/signup/components/SignUpForm.module.scss
Labels: chore

#250 [Fix/#242] 토큰 만료 관련 처리
  app/(base)/components/BottomSection.module.scss
  app/(base)/member/daily-routine/components/HabitList.module.scss
  app/(base)/member/daily-routine/components/HabitList.tsx
  app/(base)/member/layout.tsx
  app/(base)/member/profile/page.tsx
  app/(base)/page.module.scss
  app/admin/layout.tsx
  app/admin/page.tsx
  app/api/members/test-habits/route.ts
  middleware.ts
  utils/fetcher.ts
Labels: fix

#256 [style/#255] 오늘의 루틴페이지 css 수정
  app/(base)/member/daily-routine/components/HabitList.module.scss
Labels: chore

#258 [style/#257] 기록보기페이지 css 수정
  app/(base)/member/record/components/TestRecordList.module.scss
Labels: chore

#260 [style/#259] 로딩페이지 css 수정
  app/components/Loading.module.scss
  app/components/Loading.tsx
Labels: chore

#263 [style/#262] 오늘의루틴페이지에서 습관명에 마우스 호버시 마우스모양 포인터로 수정
  app/(base)/member/daily-routine/components/HabitList.module.scss
  app/(base)/member/record/components/TestRecordList.module.scss
Labels: chore

#265 [feat/#264] 오늘의루틴페이지에서 포기,수정 버튼 전체 기간 중 80%가 되면 안보여야 하는데 달성률이 80%가 되면 안보이게 되서 해당 부분 수정
  application/usecase/habit/GetOngoingHabitsUsecase.ts
Labels: chore

#268 [feat/#201] : 좋아요 상태 UI변화 로컬에서 처리
  app/(base)/member/message/components/LikeButton.tsx
  app/(base)/member/message/components/MessageItem.tsx
Labels: feat

#267 [fix/#202] useMessages에 SWR refresh interval 추가
  hooks/useMessages.ts
Labels: fix

#273 [fix/#272] 카테고리 이름 중복 시 에러 핸들링 안되는 이슈 수정
  app/admin/components/CategoryItem.tsx
  hooks/useAdminCategories.ts
  infra/repositories/supabase/SbCategoryRepository.ts
  utils/fetcher.ts
Labels: fix

#277 [chore/#276] 로그 주석처리
  app/(auth)/signup/components/SignUpForm.tsx
  app/(base)/member/components/modals/ViewHabitModal.tsx
  app/api/members/messages/route.ts
  infra/repositories/supabase/SbHabitRecordRepository.ts
  infra/repositories/supabase/SbMessageLikeRepository.ts
  infra/repositories/supabase/SbMessageRepository.ts
Labels: chore

#280 [feat/#279] 기록보기페이지 페이지네이션 추가
  app/(base)/member/record/components/TestRecordList.tsx
  app/(base)/member/record/page.tsx
Labels: feat

#282 [chore/#281] 기록보기 page.tsx 사용안하는 부분 주석처리
  app/(base)/member/record/page.tsx
Labels: chore

#284 [chore/#283] 기록보기페이지 css 수정 및 습관 없을때도 페이저 나오는 부분 수정
  app/(base)/member/record/components/TestRecordList.module.scss
  app/(base)/member/record/components/TestRecordList.tsx
Labels: chore

#286 [chore/#285] config 수정
  next.config.ts
Labels: chore

#291 [chore/#290] 기록보기페이지에서 포기 하단에 멘트 수정
  app/(base)/member/record/components/TestRecordList.tsx
Labels: chore

#292 [chore/#289] : 메시지 없으면 페이저 안보이게 수정
  app/(base)/member/daily-routine/components/DailyMessage.tsx
Labels: chore

#294 [chore/#293] 리드미 초안
  README.md
Labels: chore
